### PR TITLE
Update linger_rx.py

### PR DESCRIPTION
**Pull request by cobygoldstein**
Hello,

I've been trying to run your program, but I am having trouble where it keeps saying that something went wrong enabling the monitor mode. Could you give some advice on what I could do to solve this problem?

### CODE REVIEW

**Comment by javl** [comment]
Please make sure you make the edits in your own fork of the projects, instead of creating pull requests in upstream (the original repo). Just clone your own fork (git clone https://github.com/cobbles333/linger.git) and make edits in there.

What kind of error are you getting when you try to enable monitor mode, and does it work when you run the code directly in your own terminal? (sudo airmon-ng start wlan0)

**Comment by cobygoldstein** [comment]
I have not been enabling monitor mode directly, I have been trying to run the linger_rx, and when i go to the logs to find out whats wrong it shows that "Something went wrong enabling monitor mode." but, when I put sudo airmon-ng start wlan0 into the command line, it says that on wlan1, monitor mode is already enabled. Thank you for any help!

**Comment by javl** [comment]
Ok, so device `wlan1` does support monitor mode, good to know. When you run `sudo airmon-ng` (no arguments) it should show you a list of all interfaces. I take it it shows you `wlan1` and `mon0`?
Because the Linger script already starts the monitor mode, you need to disable it again before running, so first run `sudo airmon-ng stop wlan1` to make sure it is disabled, then run the ./linger_tx.py script.

When running Linger, what is the error you're getting? Also, try running it with the `-vvv` argument to get as much verbose info as possible.

**Comment by cobygoldstein** [comment]
when I run sudo airmon-ng , it only displays wlan0 and wlan1. what code should I run to start the linger_rx?

**Comment by javl** [comment]
Again, please try to first enable monitor mode directly. If you run into problems with my script there are too many variables to know what causes the problem, so we need to narrow it down. Running monitor mode directly will help us to make sure the problem is not with that part.
1. Easiest way to make sure everything has been reset is to reboot your system.
2. Ignore linger_rx.py for now, just open a terminal window
3. Run `sudo airmon-ng` and note the list of interfaces, looking at your previous post it should show a list with `wlan0` and `wlan1`
4. Run `sudo airmon-ng start wlan1`. It should say something along the lines of 'monitor mode enabled on mon0'. If not, report back what message you get.

**Comment by cobygoldstein** [comment]
Thank you, unfortunately, it says on the same line as wlan1, r8188eu (monitor mode enabled)

I assume that this means that monitor mode is enabled on wlan1 not mon0. How could I get mon0 enabled?

**Pull request closed without merging**
